# @package _global_

# to execute this experiment run:
# python run.py experiment=example_simple.yaml

defaults:
  - override /trainer: four_2080tis
  - override /dataset: default
  - override /callbacks: default
  - override /model: v2_large
  - override /logger: wandb

trainer:
  check_val_every_n_epoch: 10
  deterministic: true

dataset:
  batch_size: 4